services:
  neo4j:
    image: neo4j:5.23.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test_1234
    volumes:
      - ./data:/data
      - ./logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
 
  