
services:
  rancher:
    image: rancher/rancher:v2.4.9
    container_name: rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "4000:80"
      - "4443:443"
    volumes:
      - ./data/lib:/var/lib
      - ./data/log:/var/log