version: '3.3'
services:
  app:
    image: ubuntu:jammy
    container_name: sqlstudio_server
    restart: always
    ports:
      - 18888:18888
    volumes:
      - ./sqlynx:/sqlynx
    command: sh -c "/sqlynx/maicong-sqlynx.sh; sh /sqlynx/maicong-sqlynx.sh start"