services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: my_password
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data