# To run a specific version of Jaeger, use environment variable, e.g.:
#     JAEGER_VERSION=2.0.0 HOTROD_VERSION=1.63.0 docker compose up

services:
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "5778:5778"
      - "9411:9411"
      # 和 opentelemetry-collector 二选一 jaeger 不支持 log 和metrics 都用就得改映射端口
      - "14317:4317"
      - "14318:4318"
    environment:
      - LOG_LEVEL=debug

  # hotrod:
  #   image: jaegertracing/example-hotrod:1.68.0
  #   # To run the latest trunk build, find the tag at Docker Hub and use the line below
  #   # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
  #   #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #     - "8082:8082"
  #     - "8083:8083"
  #   command: ["all"]
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.246.22:4318