# To run a specific version of Jaeger, use environment variable, e.g.:
#     JAEGER_VERSION=2.0.0 HOTROD_VERSION=1.63.0 docker compose up

services:
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "5778:5778"
      - "9411:9411"
      # 和 opentelemetry-collector 二选一 jaeger 不支持 log 和metrics 都用就得改映射端口
      - "14317:4317"
      - "14318:4318"
    environment:
      - LOG_LEVEL=debug
