server:
  http_listen_port: 9080
  grpc_listen_port: 4317

positions:
  filename: /tmp/positions.yaml  # 记录文件读取的位置，避免日志重复处理

clients:
  - url: http://192.168.246.22:3100/api/prom/push  # Loki 的接收端口

scrape_configs:
  - job_name: "system"
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/*log  # 收集宿主机上所有的日志文件
