services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    mem_limit: 4GB
    restart: unless-stopped
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - xpack.ml.use_auto_machine_memory_percent=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -u elastic:changeme http://localhost:9200/_cluster/health | grep -E '\"status\":\"(green|yellow)\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://${ES_IP}:${ES_PORT}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=Rul0Shv8hYC-YVFK9sj7
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

      # elasticsearch bin/elasticsearch-reset-password -u kibana_system
