
services:
  jenkins:
    image: jenkins/jenkins:2.426.2-lts-jdk17
    container_name: jenkins
    privileged: true
    user: "root"
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home