
services:
  mysql:
    container_name: local_mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s