
services:
  mysql:
    container_name: local_mysql
    image: mysql:8.4.0
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always