
services:
  minioDB:
    container_name: minio
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    command: server /data --console-address ":9080"
    ports:
      - 9080:9080
      - ${MINIO_PORT}:9000
    restart: always
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}