
services:
  minioDB:
    container_name: minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ":9080"
    ports:
      - 9080:9080
      - 9000:9000
    restart: always
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789